# Generated by Django 5.2.2 on 2025-06-04 23:08

import django.db.models.deletion
import misc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('preview', models.TextField(blank=True, null=True)),
                ('standalone', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('page_title', models.CharField(max_length=300, unique=True)),
                ('page_url', models.CharField(max_length=300, unique=True)),
                ('cover_image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('date', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_file', models.FileField(upload_to=misc.models.path_file_name)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='variable',
            field=models.ManyToManyField(blank=True, to='misc.variable'),
        ),
    ]
